//
// Generated file, do not edit! Created by nedtool 5.6 from message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>message.msg:1</tt> by nedtool.
 * <pre>
 * message rMessage
 * {
 *     simtime_t startTime;
 *     simtime_t tmpStartTime;
 * }
 * </pre>
 */
class rMessage : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::simtime_t startTime;
    ::omnetpp::simtime_t tmpStartTime;

  private:
    void copy(const rMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const rMessage&);

  public:
    rMessage(const char *name=nullptr, short kind=0);
    rMessage(const rMessage& other);
    virtual ~rMessage();
    rMessage& operator=(const rMessage& other);
    virtual rMessage *dup() const override {return new rMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getStartTime() const;
    virtual void setStartTime(::omnetpp::simtime_t startTime);
    virtual ::omnetpp::simtime_t getTmpStartTime() const;
    virtual void setTmpStartTime(::omnetpp::simtime_t tmpStartTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const rMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, rMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MESSAGE_M_H

